Staging feature/login
DaikoneKisu/uchamba-frontend pull request #2
Opened 2023-11-30 13:16 UTC by DaikoneKisu

2023-12-03 18:40 UTC, Noralgorithm requested changes

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(auth)/login/Form.svelte
Falta formatear el código, hay errores de indentación

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(auth)/login/+page.server.ts
> +        throw redirect(StatusCodes.SEE_OTHER, `/${redirectTo}`)
Acá el "/" ya viene en el URL param, por lo que hay quitarlo de acá para evitar que cuando te redireccione se interprete como una URL absoluta. En su defecto, se podría quitar el "/" del valor almacenado en la URL y que siempre se la añada acá, ambas opciones solucionan el problema.
```suggestion
        throw redirect(StatusCodes.SEE_OTHER, `${redirectTo}`)
```

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(auth)/login/+page.server.ts
Faltó formatear el código del archivo

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(auth)/login/+page.svelte
Faltó formatear el código del archivo

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(auth)/login/login-fail-data.type.ts
Faltó formatear el código del archivo

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(auth)/login/user-schema.ts
Faltó formatear el código del archivo

2023-12-03 18:40 UTC, Noralgorithm commented on src/routes/(authed)/+layout.server.ts
Faltó formatear el código del archivo

2023-12-03 18:40 UTC, Noralgorithm commented on tailwind.config.js
Falta formatear el código, pero la configuración del DarkMode no se debería hacer en esta rama

2023-12-03 18:42 UTC, Noralgorithm requested changes

2023-12-03 18:42 UTC, Noralgorithm commented on src/routes/(auth)/login/+page.svelte
> +	})
No entiendo para qué está esto

2023-12-10 11:58 UTC, Hector1567XD commented on src/routes/(auth)/login/+page.svelte
> +	})
La verdad yo tampoco, que diablos estan haciendo aqui 🤨

2023-12-10 12:01 UTC, Hector1567XD commented on src/routes/(auth)/login/+page.server.ts
> +      const session = await fetch('https://uchamba-backend-staging.1.us-1.fl0.io/auth/login', {
Ok pero
```suggestion
      const session = await fetch(`${BASE_URL}/auth/login`, {
```

2023-12-21 05:43 UTC, DaikoneKisu commented on src/routes/(auth)/login/+page.server.ts
> +      const session = await fetch('https://uchamba-backend-staging.1.us-1.fl0.io/auth/login', {
xd, gracias

2023-12-21 18:37 UTC, Paulaforero requested changes
Los inputs se ven muy grandes, al igual que los elementos en la página, los mensajes de aviso en los inputs deben estar alineados a la izquierda y tratar de que cuando aparezcan no se rueden los inputs ya que se ve algo raro. También mejorar el placeholder del input para dar un mejor ejemplo de como es el formato del correo UCAB.

2023-12-21 20:41 UTC, DaikoneKisu commented on src/routes/(auth)/login/+page.server.ts
> +      const session = await fetch('https://uchamba-backend-staging.1.us-1.fl0.io/auth/login', {
Lito

2023-12-24 02:05 UTC, DaikoneKisu commented on src/routes/(auth)/login/+page.server.ts
> +        throw redirect(StatusCodes.SEE_OTHER, `/${redirectTo}`)
Listo

2023-12-24 02:08 UTC, DaikoneKisu commented on tailwind.config.js
Fuck Single Responsibility Principle

2023-12-24 02:10 UTC, DaikoneKisu commented on src/routes/(auth)/login/+page.svelte
> +	})
Yo menos, se corrige después

2023-12-24 02:52 UTC, Noralgorithm approved these changes
lgtm

2023-12-27 00:01 UTC, Paulaforero approved these changes

2023-12-27 11:55 UTC, Hector1567XD approved these changes
Noc de Svelte, pero si se que estas bello <3

2023-12-27 13:30 UTC, merged

2023-12-27 13:30 UTC, DaikoneKisu commented
Se logró señores