Improvement/login/changes to login screen
DaikoneKisu/uchamba-frontend pull request #3
Opened 2023-12-19 23:58 UTC by mariagiorgetti

2023-12-21 04:58 UTC, DaikoneKisu requested changes
Revisar

2023-12-21 04:58 UTC, DaikoneKisu commented on package-lock.json
¿Estás usando npm? Debes usar pnpm y borrar este archivo para evitar fallos de compatibilidad

2023-12-21 04:58 UTC, DaikoneKisu commented on src/lib/components/sign-up-log-in-switch-button/SignUpLogInSwitchButton.svelte
@Noralgorithm ¿Debiera seguir existiendo este archivo? Como ya no tenemos sign up, lo veo innecesario, más que por retrocompatibilidad

2023-12-21 04:58 UTC, DaikoneKisu commented on src/lib/components/sign-up-log-in-switch-button/sign-up-log-in-switch-button.test.ts
@Noralgorithm lo mismo que para el archivo que testea

2023-12-21 04:58 UTC, DaikoneKisu commented on src/lib/images/edificio.png
¿Quizás un cambio de nombre de edificio.png a login-image.png le caería bien? @Noralgorithm @Paulaforero

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/sign-up/+page.svelte
Borrar este archivo y todo /sign-up

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +	import './layout.css';
¿Por qué usar css si usamos tailwind? Borrar esta línea en cuanto se adapten los estilos que están ahí a tailwind

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +	import '../../app.css'
Dejar de importar esto aquí

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +	import firstLoginImage from '$lib/images/edificio.png'
```suggestion
	import loginImage from '$lib/images/login-image.png'
```
Hacer eso si se decide cambiarle el nombre a login-image.png, sino:
```suggestion
	import edificio from '$lib/images/edificio.png'
```

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +	import secondLoginImage from '$lib/images/login-image-two.png'
```suggestion
```
Borrar esto porque no se usa

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +	import SignUpLogInSwitchButton from '$lib/components/sign-up-log-in-switch-button/SignUpLogInSwitchButton.svelte'
```suggestion
```
Borrar esto porque no se usa

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +	}
```suggestion
```
Borrar todo esto porque no se usa

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +        <img src={ucabLogo} alt="logo de la ucab" class="max-w-[497px] aspect-[497/75] overflow-hidden mt-custom" />
```suggestion
        <img src={ucabLogo} alt="logo de la ucab" class="max-w-[497px] aspect-[497/75] overflow-hidden mt-16" />
```
Usar verdaderas clases de tailwind, no inventes las tuyas propias

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +    <div class="min-h-screen flex flex-col items-center justify-start  pb-24 pt-10 w-1/2">
¿Por qué este div? ¿Por qué no aplicar estas clases al elemento main? Intentar refactorizar para que sea posible

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +        <img src={firstLoginImage} alt=""
```suggestion
        <img src={loginImage} alt=""
```
o
```suggestion
        <img src={edificio} alt=""
```
dependiendo de cuál nombre se acepte para ese archivo

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +            "
```suggestion
```
Usar tailwind para esto

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +            "
Aparte, ¿por qué posicionar la imagen absolutamente?

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/+layout.svelte
> +            "
Incluso, ¿por qué posicionar la imagen dentro del elemento main? Debiera estar fuera

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(auth)/layout.css
Pasar los estilos de este archivo a +layout.svelte en forma de clases de tailwind y borrar este archivo

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/(authed)/+page.svelte
> +	import '../../app.css'
```suggestion
```
Borrarlo porque debiera de importarse en el +layout.svelte en /src/routes

2023-12-21 04:58 UTC, DaikoneKisu commented on src/routes/+layout.svelte
```suggestion
<script>
	import '../app.css'
</script>

<slot />
```
Dicho de otro modo, volver a crear este archivo con sus contenidos previos

2023-12-21 04:58 UTC, DaikoneKisu commented on src/lib/images/login-image-one.png
Borrar esta imagen porque no se usa (creo, chequear bien)

2023-12-21 04:58 UTC, DaikoneKisu commented on src/lib/images/login-image-two.png
Borrar esta imagen porque no se usa

2023-12-21 06:37 UTC, Noralgorithm requested changes

2023-12-21 06:37 UTC, Noralgorithm commented on src/lib/components/input/Input.svelte
Hay que mergear la rama feature/input para tener los últimos cambios presentes acá.

2023-12-21 06:37 UTC, Noralgorithm commented on src/lib/components/sign-up-log-in-switch-button/SignUpLogInSwitchButton.svelte
No debería

2023-12-21 06:37 UTC, Noralgorithm commented on src/lib/components/sign-up-log-in-switch-button/sign-up-log-in-switch-button.test.ts
Tampoco debería

2023-12-21 06:37 UTC, Noralgorithm commented on src/lib/images/edificio.png
Sí sería un mejor nombre, igual el nombre puede que cambie a futuro si se llega a implementar lo de las múltiples imágenes cambiantes.

2023-12-21 06:37 UTC, Noralgorithm commented on src/lib/images/login-image-one.png
Confirmo

2023-12-21 06:37 UTC, Noralgorithm commented on src/routes/(auth)/sign-up/+page.svelte
Sí, se deben borrar porque no tenemos registro en nuestra plataforma por los momentos

2023-12-21 13:02 UTC, Hector1567XD commented on package-lock.json
De pana

2023-12-21 17:08 UTC, Paulaforero requested changes
Las proporciones de toda la página son muy grades, recomiendo hacer los elementos más pequeños en la página tienes el tamaño de los inputs en 400x76 y en el figma estan en 330x64. Para el tamaño del bienvenidos y el logo de la universidad trata de que el bienvenidos este alineado con el logo que esten del mismo tamaño, a penas comienza el logo abajo comienza el bienvenidos, se soluciona haciendo el bienvenidos más pequeño (ya mando una foto 
![photo1703177902](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/a0c65042-62f4-4809-b5d8-dd37f3a3f0f4)
). La foto esta bien pero recuerda que los bordes cambiaron y ya no son así (adjunto otra imágen 
![photo1703178117](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/6af40076-42dd-47a6-8a1d-4cc2294ca77a)
). Para el diseño responsive a pesar de que no esta en el figma (falta de tiempo) lo que harás es que cuando la página se haga más pequeña se eliminará la foto y el form de iniciar sesión quedará en el medio (cuando digo el form de iniciar sesión me refiero a esto 
![photo1703178311](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/29ca2403-116d-4416-b659-aa95fd970bc9)
) Cualquier duda o algo que no hayas entendido me avisas y vamos al dc

2023-12-22 03:03 UTC, Paulaforero commented
Para los mensajes de error después de que se escribe algo en los inputs hay que alinearlos a la izquierda y que no se rueda para abajo los inputs

2023-12-26 22:41 UTC, Paulaforero requested changes
La imagen esta bien, pero te falta poner los títulos un poco más pequeños, además los mensajes de error de los inputs tienen que estar alineados a la izquierda, no deben estar centrados, y no se deben de rodar los inputs cuando aparece esos mensajes. 
![Uploading photo1703630467.jpeg…]()

Las letras del botón deben de estar en blanco 
![photo1703630205](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/f84f0e9c-331f-4cda-b52c-0e184508c85a)

2024-01-08 02:04 UTC, merged