Feature/profile with login
DaikoneKisu/uchamba-frontend pull request #4
Opened 2023-12-23 20:38 UTC by Noralgorithm

2023-12-23 23:03 UTC, Paulaforero requested changes
- Bug con la barra de la nav bar (![photo1703368193](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/7e28f2a3-3d47-46df-a8e8-3c6a37d601e4)
)

- Este input no parece que tiene el mismo tamaño que los demás como por ejemplo los que están en el modal de información personal (
![photo1703368363](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/fe500455-7253-4324-b1d1-96c5d0817653)
)

- Se puede hacer con respecto a los iconos del modal para que no se vean borrosos? 
(no se si solo me pasa a mi)

- Creo que esto es una tarea para daikone pero es necesario los mensajes de error y de sucess cuando se añada nueva información, se edita, se elimina, etc
- El mensaje de "¿Seguro que desea eliminar esta formación académica?" debe estar tambien para los links
- Que se muestre la ñ y acentos necesarios para los idiomas (recuerden que así mismo se muestra en el CV y no es bueno que este mal escrito)

- Algo importante es que no puedas eliminar tu idioma nativo, SI O SI un egresado debe tenerlo, algo así como ocurre en las formación académica con el pregrado de la ucab, creo que si se puede editar el propio idioma pero el nivel debe estar desactivado. Este idioma debe estar de primero siempre.
- Las recomendaciones de las habilidades deben estar en español.
- Acomodar el placeholder (
![photo1703370041](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/c1224d6f-1d07-4532-b6a3-9a4ad135f509)
).

- No esta haciendo la validación de que la la fecha de salida debe ser después de la de entrada en las experiencias laborales.
- No se muestra de forma correcta una experiencia laboral al darle a más información (
![photo1703370434](https://github.com/DaikoneKisu/uchamba-frontend/assets/94322466/a94c0831-9483-46a0-8730-16adaa2752c4)
)
-Como estamos trabajando con los check no deberia salir "opcional" en el input de fecha de salida de las experiencias laborales.

- Al editar una experiencia laboral no se están mostrando las fechas, eso es por que el formato que envía el backend no concuerda con el del input.
- Al editar debería recordar que ya al añadir una experiencia laboral seleccione freelancer.
- Bug al crear un proyecto y añadir una imágen, borrarla y volver a subir la imágen no te deja.
- Me da error al editar un proyecto cuando quiero cambiar la descripción, nombre, y link pero cuando cambio alguna imagen no me salta el error (para una mejor explicación escribir por priv jejje)
- Refactorización del ver del perfil (no se puede ver la información personal, tampoco que se pueda editar el portafolio, tambien acomodar como se ve el ver mas informacion de las experiencias laborales)

2023-12-29 06:41 UTC, DaikoneKisu requested changes
Bueno, ahi está la prueba de caja blanca

2023-12-29 06:41 UTC, DaikoneKisu commented on package-lock.json
¿Qué hace esto aquí? ¿npm?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/input-with-icon/InputWithIcon.svelte
> +  import type { HTMLInputTypeAttribute } from '../../../types/html-input-type-attribute.type'
```suggestion
  import type { HTMLInputTypeAttribute } from '$lib/types/html-input-type-attribute.type'
```
Claro, esto implica mover el html-input-type-attribute a types en lib

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/input/Input.svelte
> +  import type { HTMLInputTypeAttribute } from '../../../types/html-input-type-attribute.type'
```suggestion
  import { fly } from 'svelte/transition'
  
  import type { HTMLInputTypeAttribute } from '$lib/types/html-input-type-attribute.type'
```
El espacio para mantener el estilo de imports del mismo tipo (de módulos del lenguaje, de módulos third party y de módulos propios) 
Lo segundo implica mover el html-input-type-attribute a types en lib

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/input/Input.svelte
> +    >
```suggestion
    <strong class="invisible ml-3 w-[80%] text-left text-[12px] text-red-600" aria-hidden
      ></strong
    >
```
Preferible, y ¿por qué el w-[80%]?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/input/Input.svelte
> +    >
También hay que buscar la forma de que la animación se ejecute en caso de distintos errores, si es muy complicado/consume mucho tiempo, avisarme para colocarlo como tarea aparte

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/password-input/password-input.test.ts
> +import PasswordInput__SvelteComponent_ from './PasswordInput.svelte'
```suggestion
import { render, screen } from '@testing-library/svelte'
import { describe, expect, test } from 'vitest'

import PasswordInput__SvelteComponent_ from './PasswordInput.svelte'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/password-input/password-input.test.ts
> +import PasswordInput__SvelteComponent_ from './PasswordInput.svelte'
Expliqué el por qué en un comentario anterior

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/expand.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
```suggestion
```
¿Por qué el comentario de desactivar?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/add/Add.svelte
> +</button>
```suggestion
<script lang="ts">
  import addIcon from '$lib/icons/add-white.svg'

  export let clickHandler: () => void
  export let altImgText = 'Añadir'
</script>

<button
  on:click={clickHandler}
  class="flex items-center justify-center gap-2 rounded-[10px] bg-ucab-green py-1 pl-5 pr-6 text-brand-white shadow-lg transition-all duration-200 hover:bg-green-600 hover:shadow-lg hover:shadow-emerald-200"
>
  <img src={addIcon} alt={altImgText} />
  <p class="font-poppins text-[20px] font-medium">Añadir</p>
</button>
```
Aplica esta corrección si este botón de añadir es uno genérico dentro del perfil y puede estar en cualquier sección, ya que el texto alternativo a la imagen va a depender de dónde esté entonces

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +  $: prevImage = (currentImage - 1 + images.length) % images.length
```suggestion
  let currentImage = 0

  $: nextImage = (currentImage + 1) % images.length
  $: prevImage = (currentImage - 1 + images.length) % images.length

  function goNext() {
    currentImage = (currentImage + 1) % images.length
  }

  function goPrev() {
    currentImage = (currentImage - 1 + images.length) % images.length
  }
```
Debiera funcionar según https://learn.svelte.dev/tutorial/reactive-declarations

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +  }
```suggestion
  function goNext() {
    currentImage += 1 % images.length
  }
```
Para que parezca chino

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +  }
```suggestion
  function goPrev() {
    currentImage -= 1 + images.length % images.length
  }
```
Este es peor xd, doble chequea si funciona

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +        alt="Imágen del carrusel"
```suggestion
        alt="Imagen del carrusel"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +      alt="Imágen del carrusel"
```suggestion
      alt="Imagen del carrusel"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +        alt="Imágen del carrusel"
```suggestion
        alt="Imagen del carrusel"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +<div class="flex flex-col items-center justify-center gap-4">
```suggestion
<section class="flex flex-col items-center justify-center gap-4">
```
Eso para mí es un section xd

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +</div>
```suggestion
</section>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +        alt="Imágen del carrusel"
No lleva acento

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +      <img src={leftArrow} alt="Flecha izquierda" class="aspect-square w-[30px]" />
```suggestion
      <img src={leftArrow} alt="Flecha izquierda - Imagen anterior" class="aspect-square w-[30px]" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/carousel/Carousel.svelte
> +      <img src={rightArrow} alt="Flecha derecha" class="aspect-square w-[30px]" />
```suggestion
      <img src={rightArrow} alt="Flecha derecha - Imagen siguiente" class="aspect-square w-[30px]" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/expand.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
```suggestion
```
Why?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/expand.ts
> +      }
Tomando en cuenta que existe el shrink, ¿esto hace algo?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/expand.ts
> +      }
Tomando en cuenta que existe el expand, ¿esto hace algo?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +  import { expand, shrink } from './expand'
```suggestion
  import cancelIcon from '$lib/icons/cancel.svg'
  
  import { expand, shrink } from './expand'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +  export let animation: boolean = true
```suggestion
  export let animation = true
```
Creo que no hace falta especificar el tipo en este caso

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +  let chip: HTMLElement
```suggestion
  let hovered = false
  let chip: HTMLElement
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +  export let key: string
¿Para qué un atributo key que luego se usa como id?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +    <b class="font-normal">{text}</b>
```suggestion
    <strong class="font-normal">{text}</strong>
```
Esto si quieres resaltar que este texto es más importante que el que está alrededor, si nomás querías resaltarlo sin que fuese más importante como  tal, deja el b

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +    <b class="font-normal">{text}</b>
```suggestion
    <strong class="font-normal">{text}</strong>
```
Esto si quieres resaltar que este texto es más importante que el que está alrededor, si nomás querías resaltarlo sin que fuese más importante como tal, deja el b

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/empty-list-message/EmptyListMessage.svelte
¿Y esto qué? xd

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +  import { slide } from 'svelte/transition'
```suggestion
  import { slide } from 'svelte/transition'
  
  import deleteIcon from '$lib/icons/delete.svg'
  import uploadIcon from '$lib/icons/upload.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +  export let isDeletable: boolean = true
```suggestion
  export let isDeletable = true
```
Creo que no hace falta especificar el tipo

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +  export let imageUrl: string = ''
```suggestion
  export let imageUrl = ''
```
Creo que no have falta especificar el tipo

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +  out:slide
```suggestion
  transition:slide
```
https://learn.svelte.dev/tutorial/transition

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +          <img src={deleteIcon} alt="Delete img" />
```suggestion
          <img src={deleteIcon} alt="Borrar imagen" />
```
Español al usuario porfavo

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +    <img src={uploadIcon} alt="" />
```suggestion
    <img src={uploadIcon} alt="Sube una imagen" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/image-input/ImageInput.svelte
> +    <img src={imageUrl} alt="" class="relative h-full w-full object-contain" />
```suggestion
    <img src={imageUrl} alt="Imagen subida por el usuario" class="relative h-full w-full object-contain" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/DeleteModal.svelte
> +</script>
```suggestion
<script lang="ts">
  import Modal from './Modal.svelte'

  export let title: string
  export let isOpen = false
  export let handleDelete: () => Promise<void> | void
  
  let disabled = false

  function closeModal() {
    isOpen = false
  }
</script>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/DeleteModal.svelte
> +  export let handleDelete: () => Promise<void> | void
O soy void o te prometo que seré void 😶

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/DeleteModal.svelte
> +  export let handleDelete: () => Promise<void> | void
```suggestion
  export let handleDelete: () => Promise<void>
```
Creo que es mejor reducirlo a esto y wrapear el void en una promesa, si no es tan complicado de implementar

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/Modal.svelte
> +  import { fade, scale } from 'svelte/transition'
```suggestion
  import { fade, scale } from 'svelte/transition'
  
  import cancelIcon from '$lib/icons/cancel-black.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/Modal.svelte
> +  export let isOpen: Boolean
```suggestion
  export let isOpen: boolean
```
El linter falló aquí

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/Modal.svelte
> +    out:fade={{ duration: 100 }}
```suggestion
    transition:fade={{ duration: 100 }}
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/Modal.svelte
> +  <div
```suggestion
  <article
```
Me fumé un porro con esto

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/Modal.svelte
> +  </div>
```suggestion
  </article>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/Modal.svelte
> +            <p class="text-brand-p-black">{subtitle}</p>
```suggestion
            <h3 class="text-brand-p-black">{subtitle}</h3>
```
xd

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/modal/SaveModalFooter.svelte
> +  export let disabled: boolean
```suggestion
  export let handleSave: () => void
  export let disabled: boolean
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/textbox/Textbox.svelte
> +        {disabled}
```suggestion
        {name}
        {placeholder}
        {required}
        {disabled}
        bind:value
        class="h-full resize-none text-sm focus:border-0 focus:shadow-none focus:outline-none"
```
Porfa

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/textbox/Textbox.svelte
> +      >Has como que no estás leyendo esto</span
```suggestion
      >Haz como que no estás leyendo esto</span
```
Es con z

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/profile/textbox/Textbox.svelte
> +    <span class="invisible ml-3 text-[12px] text-red-600" aria-hidden
Lo de text-[12px] debiera estar en el app.css para evitar repetirlo a cada rato

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/sign-up-log-in-switch-button/SignUpLogInSwitchButton.svelte
Borrar esto

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/components/sign-up-log-in-switch-button/sign-up-log-in-switch-button.test.ts
Borrar esto

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/icons/Portfolio.svg
portfolio.svg en vez de Portfolio.svg

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/profile/experience/validate-academic-experience.ts
> +  entryDate: date().nullable().default(null).required('Campo requerido'),
```suggestion
  entryDate: date().required('Campo requerido'),
```
required anula el efecto de nullable

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/profile/experience/validate-academic-experience.ts
> +  freelancer: boolean(),
```suggestion
    }),
  freelancer: boolean().default(false),
```
El valor por defecto debiera ser false, por interfaz

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/profile/personal-information/validate-personal-information.ts
> +  email: string().required('Campo requerido').email('Email inválido'),
Esta validación no debiera ser la de email sino la de correo ucab, creo que en login está implementada

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/profile/portfolio/project-creation-payload.type.ts
> +  images: Array<File | null>
¿Es un arreglo de archivos o un arreglo de nulls? ¿O es un arreglo de archivos o null? Si es lo segundo, este tipo no indica eso

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/profile/portfolio/project-edition-payload.ts
> +  images: Array<File | null>
¿Es un arreglo de archivos o un arreglo de nulls? ¿O es un arreglo de archivos o null? Si es lo segundo, este tipo no indica eso

2023-12-29 06:41 UTC, DaikoneKisu commented on src/lib/profile/portfolio/validate-project.ts
El uso de mixed aquí lo veo raro, quizás array sería mejor https://www.npmjs.com/package/yup#array
Y para la coverImage, dunno, ¿string?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/education/languages/update/+server.ts
> +export async function POST({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```suggestion
export async function PUT({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```
Como actualiza algo existente, debiera ser un PUT en vez de un POST. Y sí, SvelteKit sí lo soporta https://learn.svelte.dev/tutorial/other-handlers

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/education/academic-training/update/+server.ts
> +export async function POST({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```suggestion
export async function PUT({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```
Como actualiza algo existente, debiera ser un PUT en vez de un POST. Y sí, SvelteKit sí lo soporta https://learn.svelte.dev/tutorial/other-handlers

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/experience/academic-experience/delete/+server.ts
> +export async function POST({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```suggestion
export async function DELETE({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```
¿Por qué esto es un POST?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/experience/academic-experience/update/+server.ts
> +export async function POST({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```suggestion
export async function PUT({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```
Como actualiza algo existente, debiera ser un PUT en vez de un POST. Y sí, SvelteKit sí lo soporta https://learn.svelte.dev/tutorial/other-handlers

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/personal-information/update/+server.ts
> +export async function PUT({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
¿Ves? Aquí sí usaste PUT, bien hecho

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/personal-links/delete/+server.ts
> +export async function POST({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```suggestion
export async function DELETE({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/portfolio/projects/create/+server.ts
¿Y la interfaz que representa el payload de creación?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/api/profile/portfolio/projects/update/+server.ts
¿Y la interfaz que representa el payload de actualizar?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.server.ts
> +import { redirect, type Cookies } from '@sveltejs/kit'
```suggestion
import { redirect, type Cookies } from '@sveltejs/kit'
import { BACKEND_BASE_URL } from '$env/static/private'

import type { ProfileData } from '$lib/types/profile-data.type'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.server.ts
> +  params: { id },
```suggestion
  params,
```
Creo que estás especificando el tipo dos veces

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.server.ts
> +  const isLoggedUser = id === 'me'
```suggestion
  const accessingMyProfile = id === 'me'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.server.ts
> +  if (isLoggedUser) {
```suggestion
  if (accessingMyProfile) {
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.svelte
> +  import PersonalLinks from './PersonalLinks.svelte'
```suggestion
  import Header from './Header.svelte'
  import PersonalInformation from './PersonalInformation.svelte'
  import PersonalLinks from './PersonalLinks.svelte'
  
  import pencilIcon from '$lib/icons/pencil.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.svelte
> +  import PersonalLinks from './PersonalLinks.svelte'
100% opinionado

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.svelte
> +      alert(e)
Supongo que esto está así hasta que tengamos el alert genérico, ¿no? Por otro lado, este error debiera ser revisado y traducido para que el usuario pueda entenderlo, actualmente podría fallar el res.blob() y lanzar un error cualquiera de runtime completamente inentendible para el usuario, por dar un ejemplo

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/+layout.svelte
> +    link.download = 'CV.pdf'
```suggestion
    link.download = `${data.name.split(' ').join('-').toLowerCase()}.pdf`
```
Creo que se vería mejor así el nombre del CV (Nombre de la persona en kebab case). De igual manera, esto cambiará luego otra vez

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/Header.svelte
> +  $: currentRoute = $page.url.pathname.split('/').pop() as 'education' | 'experience' | 'portfolio'
¿Esto tiene que ser una reactive declaration?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/Header.svelte
> +          class="flex h-full w-full flex-col items-center justify-center gap-2"
```suggestion
          class="flex h-full w-full flex-col items-center justify-center gap-2 uppercase"
```
Si quieres que se muestre en uppercase, no debieras depender de que en el html se escriba en uppercase

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/Header.svelte
> +          class="flex h-full w-full flex-col items-center justify-center gap-2"
```suggestion
          class="flex h-full w-full flex-col items-center justify-center gap-2 uppercase"
```
Si quieres que se muestre en uppercase, no debieras depender de que en el html se escriba en uppercase

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/Header.svelte
> +          class="flex h-full w-full flex-col items-center justify-center gap-2"
```suggestion
          class="flex h-full w-full flex-col items-center justify-center gap-2 uppercase"
```
Si quieres que se muestre en uppercase, no debieras depender de que en el html se escriba en uppercase

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalInformation.svelte
> +  import PersonalInformationEditionModal from './PersonalInformationEditionModal.svelte'
```suggestion
  import type { ProfileData } from '$lib/types/profile-data.type'
  
  import PersonalInformationEditionModal from './PersonalInformationEditionModal.svelte'
  
  import pencilIcon from '$lib/icons/pencil.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalInformation.svelte
> +  import PersonalInformationEditionModal from './PersonalInformationEditionModal.svelte'
Completamente opinionado

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalInformationEditionModal.svelte
> +  import { ValidationError } from 'yup'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import Textbox from '$lib/components/profile/textbox/Textbox.svelte'
  import { validatePersonalInformation } from '$lib/profile/personal-information/validate-personal-information'
  
  import userIcon from '$lib/icons/user.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalInformationEditionModal.svelte
> +      alert(e)
Sanear este error y prepararlo mejor para mostrarselo al usuario

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalInformationEditionModal.svelte
> +      alert(e)
Actualmente, el fetch podría fallar y se mostraría ese error al usuario, por ejemplo

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalLinkCreationModal.svelte
> +  import { ValidationError } from 'yup'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import { validatePersonalLink } from '$lib/profile/personal-links/validate-personal-link'
  
  import externalLinkIcon from '$lib/icons/external-link.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalLinkCreationModal.svelte
> +      alert(error)
Nuevamente, sanear el error

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalLinkCreationModal.svelte
> +      alert(error)
Y bueno, sanear === hacerlo user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalLinks.svelte
> +  import { slide } from 'svelte/transition'
```suggestion
  import { slide } from 'svelte/transition'
  
  import type { PersonalLink } from '$lib/types/profile-data.type'
  
  import Add from '$lib/components/profile/add/Add.svelte'
  import PersonalLinkCreationModal from './PersonalLinkCreationModal.svelte'
  
  import deleteIcon from '$lib/icons/delete.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalLinks.svelte
> +      if (!res.ok) throw new Error('Error al eliminar la formación académica')
¿Formación académica? ¿No debería decir link personal?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/PersonalLinks.svelte
> +      alert(error)
Hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/+page.svelte
Este archivo es la definición de declarativo

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +  import type { PersonalStudy } from '$lib/types/profile-data.type'
```suggestion
  import { invalidateAll } from '$app/navigation'
  import { slide } from 'svelte/transition'
  
  import type { PersonalStudy } from '$lib/types/profile-data.type'
  
  import Add from '$lib/components/profile/add/Add.svelte'
  import AcademicTrainingCreationModal from './AcademicTrainingCreationModal.svelte'
  import DeleteModal from '$lib/components/profile/modal/DeleteModal.svelte'
  import AcademicTrainingEditionModal from './AcademicTrainingEditionModal.svelte'
  
  import pencilIcon from '$lib/icons/pencil.svg'
  import deleteIcon from '$lib/icons/delete.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +      alert(error)
Hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +      <h2>Formación Académica</h2>
```suggestion
      <h2 class="capitalize">Formación Académica</h2>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +      <h2>Formación Académica</h2>
No depender de que se escriba capitalized

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +          <h3 class="font-poppins text-2xl">Universidad Católica Andrés Bello</h3>
```suggestion
          <h3 class="font-poppins text-2xl capitalize">Universidad Católica Andrés Bello</h3>
```
No depender de que esté escrito capitalized

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +        </p>
```suggestion
        <p class="text-brand-p-black capitalize">
          {featStudy.name} - {featStudy.degree}
        </p>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +        </p>
Eso también porque no sabes si el featStudy.name venga capitalizado

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +      <li in:slide out:slide class="flex flex-col gap-2">
```suggestion
      <li transition:slide class="flex flex-col gap-2">
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +      <li in:slide out:slide class="flex flex-col gap-2">
```suggestion
      <li transition:slide class="flex flex-col gap-2">
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +          <h3 class="font-poppins text-2xl">{personalStudy.universityName}</h3>
```suggestion
          <h3 class="font-poppins text-2xl capitalize">{personalStudy.universityName}</h3>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTraining.svelte
> +        </p>
```suggestion
        <p class="text-brand-p-black capitalize">
          {personalStudy.name} - {personalStudy.degree}
        </p>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/HardSkills.svelte
> +  import { fade } from 'svelte/transition'
```suggestion
  import { fade } from 'svelte/transition'
  import { flip } from 'svelte/animate'
  
  import Add from '$lib/components/profile/add/Add.svelte'
  import Chip from '$lib/components/profile/chip/Chip.svelte'
  import HardSkillCreationModal from './HardSkillCreationModal.svelte'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/HardSkills.svelte
> +      alert(e)
Hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +  import { invalidateAll } from '$app/navigation'
```suggestion
  import { invalidateAll } from '$app/navigation'
  import { slide } from 'svelte/transition'
  
  import Add from '$lib/components/profile/add/Add.svelte'
  import LanguageCreationModal from './LanguageCreationModal.svelte'
  import LanguagesDetailsModal from './LanguagesDetailsModal.svelte'
  import DeleteModal from '$lib/components/profile/modal/DeleteModal.svelte'
  
  import pencilIcon from '$lib/icons/pencil.svg'
  import deleteIcon from '$lib/icons/delete.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +
```suggestion
  let langIdToDelete: number
  
  let selectedLanguageDetails = {
    languageId: 0,
    name: '',
    proficientLevel: '',
    createdAt: '',
    updatedAt: ''
  }

  function openCreationModal() {
    openedCreationModal = true
  }

  function openDeleteModal(id: number) {
    langIdToDelete = id
    openedDeleteModal = true
  }

  function openDetailsModal(lang: {
    languageId: number
    name: string
    proficientLevel: string
    createdAt: string
    updatedAt: string
  }) {
    detailsModalMode = 'view'
    selectedLanguageDetails = { ...lang }
    openedDetailsModal = true
  }

  function openEditModal(lang: {
    languageId: number
    name: string
    proficientLevel: string
    createdAt: string
    updatedAt: string
  }) {
    detailsModalMode = 'edit'
    selectedLanguageDetails = { ...lang }
    openedDetailsModal = true
  }

```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +      alert(error)
Hacer error user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +        method: 'POST',
No lo he dicho en los previos,  pero este en particular tendría que cambiarse a DELETE

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +      <h2>Idiomas</h2>
```suggestion
      <h2 class="capitalize">Idiomas</h2>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +      <li in:slide out:slide class="flex flex-col gap-2">
```suggestion
      <li transition:slide class="flex flex-col gap-2">
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +          <h3 class="font-poppins text-2xl">{lang.name}</h3>
```suggestion
          <h3 class="font-poppins text-2xl capitalize">{lang.name}</h3>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +                <img src={pencilIcon} alt="Editar estudio" />
```suggestion
                <img src={pencilIcon} alt="Editar idioma" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +                <img src={deleteIcon} alt="Eliminar estudio" />
```suggestion
                <img src={deleteIcon} alt="Eliminar idioma" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +        <p class="text-brand-p-black">
```suggestion
        <p class="text-brand-p-black capitalize">
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +          class="text-left text-ucab-green underline underline-offset-2"
```suggestion
          class="text-left text-ucab-green underline underline-offset-2 capitalize"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/SoftSkills.svelte
> +  import { fade } from 'svelte/transition'
```suggestion
  import { fade } from 'svelte/transition'
  import { flip } from 'svelte/animate'

  import Add from '$lib/components/profile/add/Add.svelte'
  import Chip from '$lib/components/profile/chip/Chip.svelte'
  import SoftSkillCreationModal from './SoftSkillCreationModal.svelte'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/SoftSkills.svelte
> +      alert(e)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/SoftSkills.svelte
> +      <h2>Habilidades Blandas</h2>
```suggestion
      <h2 class="capitalize">Habilidades Blandas</h2>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/+page.svelte
Desde aquí se ve bonito

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/+page.svelte
> +</div>
```suggestion
<main class="flex w-full flex-col items-center justify-between gap-16 px-16 pb-28 pt-8">
  <AcademicExperience business={data.workExperiences} isEditable={data.isEditable} />
</main>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +  import { invalidateAll } from '$app/navigation'
```suggestion
  import { slide } from 'svelte/transition'
  import { invalidateAll } from '$app/navigation'
  
  import type { WorkExperience } from '$lib/types/profile-data.type'
  
  import Add from '$lib/components/profile/add/Add.svelte'
  import ExperienceCreationModal from './ExperienceCreationModal.svelte'
  import ExperienceDetailsModal from './ExperienceDetailsModal.svelte'
  import DeleteModal from '$lib/components/profile/modal/DeleteModal.svelte'
  
  import pencilIcon from '$lib/icons/pencil.svg'
  import deleteIcon from '$lib/icons/delete.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +        method: 'POST',
Debiera ser DELETE

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +      <h2>Experiencia Laboral</h2>
```suggestion
      <h2 class="capitalize">Experiencia Laboral</h2>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +      <li in:slide out:slide class="flex flex-col gap-2">
```suggestion
      <li transition:slide class="flex flex-col gap-2">
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +          <h3 class="font-poppins text-2xl">{b.organizationName}</h3>
```suggestion
          <h3 class="font-poppins text-2xl capitalize">{b.organizationName}</h3>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +                <img src={pencilIcon} alt="Editar estudio" />
```suggestion
                <img src={pencilIcon} alt="Editar experiencia académica" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +                <img src={deleteIcon} alt="Eliminar estudio" />
```suggestion
                <img src={deleteIcon} alt="Eliminar experiencia académica" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +        <p class="font-open-sans font-bold text-ucab-black">{b.jobTitle}</p>
```suggestion
        <p class="font-open-sans font-bold text-ucab-black capitalize">{b.jobTitle}</p>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/AcademicExperience.svelte
> +            class="text-left text-ucab-green underline underline-offset-2"
```suggestion
            class="text-left text-ucab-green underline underline-offset-2 capitalize"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/+page.svelte
> +</div>
```suggestion
<main class="flex w-full flex-col items-center justify-between gap-16 px-16 pb-28 pt-8">
  {#if data.isEditable}
    <Projects projects={data.projects} />
  {:else}
    <ProjectsViewList projects={data.projects} />
  {/if}
</main>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/+page.svelte
> +</div>
```suggestion
<main class="flex w-full flex-col items-center justify-between gap-16 px-16 pb-28 pt-8">
  <AcademicTraining studiesData={data.education} isEditable={data.isEditable} />
  <Languages languages={data.languages} langsList={data.langsList} isEditable={data.isEditable} />
  <SoftSkills
    softSkills={data.softSkills.featured.concat(data.softSkills.personal)}
    softSkillsList={data.softSkillsList.map((skill) => skill.name)}
    isEditable={data.isEditable}
  />
  <HardSkills
    hardSkills={data.hardSkills.featured.concat(data.hardSkills.personal)}
    hardSkillsList={data.hardSkillsList.map((skill) => skill.name)}
    isEditable={data.isEditable}
  />
</main>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +  import { ValidationError } from 'yup'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import type { ProjectCreationPayload } from '$lib/profile/portfolio/project-creation-payload.type'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import ImageInput from '$lib/components/profile/image-input/ImageInput.svelte'
  import Textbox from '$lib/components/profile/textbox/Textbox.svelte'
  import { validateProject } from '$lib/profile/portfolio/validate-project'
  
  import languageIcon from '$lib/icons/Portfolio.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +      if (!res.ok) throw new Error('Error creando el Proyecto')
```suggestion
      if (!res.ok) throw new Error('Error creando el proyecto')
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +    formData.images.push(null)
¿Para qué es el null?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +    formData.images.push(null)
¿Para qué es el null?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +          subTitle="Se admite cualquier formato de imágen"
```suggestion
          subTitle="Se admite cualquier formato de imagen"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +            subTitle="Se admite cualquier formato de imágen"
```suggestion
            subTitle="Se admite cualquier formato de imagen"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectDetailsModal.svelte
> +  import Carousel from '$lib/components/profile/carousel/Carousel.svelte'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import type { ProjectEditionPayload } from '$lib/profile/portfolio/project-edition-payload'
  import type { Project } from '$lib/types/profile-data.type'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import EditModalFooter from '$lib/components/profile/modal/EditModalFooter.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import ImageInput from '$lib/components/profile/image-input/ImageInput.svelte'
  import Textbox from '$lib/components/profile/textbox/Textbox.svelte'
  import Carousel from '$lib/components/profile/carousel/Carousel.svelte'
  import { validateProject } from '$lib/profile/portfolio/validate-project'
  
  import languageIcon from '$lib/icons/Portfolio.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectDetailsModal.svelte
> +      if (!res.ok) throw new Error('Error editando el Proyecto')
```suggestion
      if (!res.ok) throw new Error('Error editando el proyecto')
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectDetailsModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectDetailsModal.svelte
> +            subTitle="Se admite cualquier formato de imágen"
```suggestion
            subTitle="Se admite cualquier formato de imagen"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectDetailsModal.svelte
> +              subTitle="Se admite cualquier formato de imágen"
```suggestion
              subTitle="Se admite cualquier formato de imagen"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +  import type { Project } from '$lib/types/profile-data.type'
```suggestion
  import { invalidateAll } from '$app/navigation'
  import { flip } from 'svelte/animate'
  
  import type { Project } from '$lib/types/profile-data.type'
  
  import Add from '$lib/components/profile/add/Add.svelte'
  import ProjectDetailsModal from './ProjectDetailsModal.svelte'
  import ProjectCreationModal from './ProjectCreationModal.svelte'
  import DeleteModal from '$lib/components/profile/modal/DeleteModal.svelte'

  import pencilIcon from '$lib/icons/pencil.svg'
  import deleteIcon from '$lib/icons/delete.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +  let ProjectIdToDelete: number
```suggestion
  let projectIdToDelete: number
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +    ProjectIdToDelete = id
```suggestion
    projectIdToDelete = id
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +      if (!res.ok) throw new Error('Error al eliminar la Proyecto')
```suggestion
      if (!res.ok) throw new Error('Error al eliminar el proyecto')
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +  let ProjectIdToDelete: number
Recuerda cambiar el nombre en todos lados

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +        body: JSON.stringify({ id: ProjectIdToDelete })
```suggestion
        body: JSON.stringify({ id: projectIdToDelete })
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +              <img src={pencilIcon} alt="Editar estudio" />
```suggestion
              <img src={pencilIcon} alt="Editar proyecto" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/Projects.svelte
> +              <img src={deleteIcon} alt="Eliminar estudio" />
```suggestion
              <img src={deleteIcon} alt="Eliminar proyecto" />
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/portfolio/ProjectsViewList.svelte
> +  import ProjectDetailsModal from './ProjectDetailsModal.svelte'
```suggestion
  import type { Project } from '$lib/types/profile-data.type'
  
  import ProjectCard from './ProjectCard.svelte'
  import ProjectDetailsModal from './ProjectDetailsModal.svelte'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingCreationModal.svelte
> +  import { ValidationError } from 'yup'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import { validateAcademicTraining } from '$lib/profile/education/validate-academic-training'
  
  import graduationCapIcon from '$lib/icons/graduation-cap.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingCreationModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingCreationModal.svelte
> +          <option value="">Seleccione el nivel de estudios</option>
Esta opción debiera ser la default y no poder volver a seleccionarse
```suggestion
          <option value="" selected disabled>Seleccione el nivel de estudios</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingEditionModal.svelte
> +  import { ValidationError } from 'yup'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import type { PersonalStudy } from '$lib/types/profile-data.type'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import { validateAcademicTraining } from '$lib/profile/education/validate-academic-training'

  import graduationCapIcon from '$lib/icons/graduation-cap.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingEditionModal.svelte
> +        method: 'POST',
Debiera ser PUT

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingEditionModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/AcademicTrainingEditionModal.svelte
> +          <option value="">Seleccione el nivel de estudios</option>
```suggestion
          <option value="" selected disabled>Seleccione el nivel de estudios</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/HardSkillCreationModal.svelte
> +  import { fade } from 'svelte/transition'
```suggestion
  import { flip } from 'svelte/animate'
  import { fade } from 'svelte/transition'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import Chip from '$lib/components/profile/chip/Chip.svelte'
  
  import learningIcon from '$lib/icons/learning.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/HardSkillCreationModal.svelte
> +      alert(e)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/HardSkillCreationModal.svelte
> +      }}
```suggestion
      on:submit|preventDefault={() => insertSkill()}
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguageCreationModal.svelte
> +  import { ValidationError } from 'yup'
```suggestion
  import { ValidationError } from 'yup'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import { validateLanguage } from '$lib/profile/education/validate-language'
  
  import languageIcon from '$lib/icons/language.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguageCreationModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguageCreationModal.svelte
> +        <option value="">Seleccione su idioma</option>
```suggestion
        <option value="" selected disabled>Seleccione su idioma</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguageCreationModal.svelte
> +          <option value={lang.languageId}>{lang.name}</option>
```suggestion
          <option class="capitalize" value={lang.languageId}>{lang.name}</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguageCreationModal.svelte
> +        <option value="">Seleccione su nivel</option>
```suggestion
        <option value="" selected disabled>Seleccione su nivel</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +  import { invalidateAll } from '$app/navigation'
```suggestion
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import EditModalFooter from '$lib/components/profile/modal/EditModalFooter.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte
  
  import languageIcon from '$lib/icons/language.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +        method: 'POST',
Debiera ser un PUT

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +          <option value="">Seleccione su idioma</option>
```suggestion
          <option value="" disabled>Seleccione su idioma</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +          <option value={langData.languageId}>{langData.name}</option>
¿Y esta opción?

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +          <option value="">Seleccione su nivel</option>
```suggestion
          <option value="" disabled>Seleccione su nivel</option>
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/SoftSkillCreationModal.svelte
> +  import { fade } from 'svelte/transition'
```suggestion
  import { flip } from 'svelte/animate'
  import { fade } from 'svelte/transition'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import Chip from '$lib/components/profile/chip/Chip.svelte
  
  import staffIcon from '$lib/icons/staff.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/SoftSkillCreationModal.svelte
> +      alert(e)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/education/SoftSkillCreationModal.svelte
> +      }}
```suggestion
      on:submit|preventDefault={() => insertSkill()}
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceCreationModal.svelte
> +  import { slide } from 'svelte/transition'
```suggestion
  import { ValidationError } from 'yup'
  import { slide } from 'svelte/transition'
  import { invalidateAll } from '$app/navigation'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import Textbox from '$lib/components/profile/textbox/Textbox.svelte'
  import { validateAcademicExperience } from '$lib/profile/experience/validate-academic-experience'
  
  import graduationCapIcon from '$lib/icons/business.svg'
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceCreationModal.svelte
> +      if (!res.ok) throw new Error('Error al crear una experiencia academica')
```suggestion
      if (!res.ok) throw new Error('Error al crear una experiencia laboral')
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceCreationModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceCreationModal.svelte
> +        <div in:slide out:slide class="grid w-full grid-cols-2 gap-y-2">
```suggestion
        <div transition:slide class="grid w-full grid-cols-2 gap-y-2">
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceCreationModal.svelte
> +            label="Direccion"
```suggestion
            label="Dirección"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceCreationModal.svelte
> +            placeholder="Ingrese la direccion"
```suggestion
            placeholder="Ingrese la dirección"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +  import type { WorkExperience } from '$lib/types/profile-data.type'
```suggestion
  import { ValidationError } from 'yup'
  import { slide } from 'svelte/transition'
  import { invalidateAll } from '$app/navigation'
  
  import type { WorkExperience } from '$lib/types/profile-data.type'
  
  import Modal from '$lib/components/profile/modal/Modal.svelte'
  import Input from '$lib/components/input/Input.svelte'
  import EditModalFooter from '$lib/components/profile/modal/EditModalFooter.svelte'
  import SaveModalFooter from '$lib/components/profile/modal/SaveModalFooter.svelte'
  import Textbox from '$lib/components/profile/textbox/Textbox.svelte'
  import { validateAcademicExperience } from '$lib/profile/experience/validate-academic-experience'
  
  import graduationCapIcon from '$lib/icons/graduation-cap.svg'
  import business from '$lib/icons/business.svg'
  
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +  export let isEditable: boolean = true
```suggestion
  export let isEditable = true
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +  }
```suggestion
  }

```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +        method: 'POST',
Debiera ser un PUT

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +      if (!res.ok) throw new Error('Error al actualizar la experiencia academica')
```suggestion
      if (!res.ok) throw new Error('Error al actualizar la experiencia laboral')
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +      alert(error)
Mensaje típico de hacer user friendly

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              label="Direccion"
```suggestion
              label="Dirección"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              placeholder="Ingrese la direccion"
```suggestion
              placeholder="Ingrese la dirección"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +          placeholder="Ingrese el instituto o universidad"
```suggestion
          placeholder="Ingrese el nombre de la organización"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              label="Direccion"
```suggestion
              label="Dirección"
```

2023-12-29 06:41 UTC, DaikoneKisu commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              placeholder="Ingrese la direccion"
```suggestion
              placeholder="Ingrese la dirección"
```

2023-12-29 08:26 UTC, Noralgorithm commented on src/lib/components/input/Input.svelte
> +  import type { HTMLInputTypeAttribute } from '../../../types/html-input-type-attribute.type'
arreglao

2023-12-29 08:28 UTC, Noralgorithm commented on src/lib/components/input-with-icon/InputWithIcon.svelte
> +  import type { HTMLInputTypeAttribute } from '../../../types/html-input-type-attribute.type'
arreglao

2023-12-29 08:51 UTC, Noralgorithm commented on src/lib/components/input/Input.svelte
> +    >
arreglao

2023-12-29 08:54 UTC, Noralgorithm commented on src/lib/components/password-input/password-input.test.ts
> +import PasswordInput__SvelteComponent_ from './PasswordInput.svelte'
arreglao

2023-12-29 08:56 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              label="Direccion"
arreglao

2023-12-29 08:58 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              placeholder="Ingrese la direccion"
arreglao

2023-12-29 09:00 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +              label="Direccion"
arreglao

2023-12-29 09:00 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/experience/ExperienceDetailsModal.svelte
> +          placeholder="Ingrese el instituto o universidad"
arreglao

2023-12-29 09:15 UTC, Noralgorithm commented on src/lib/components/profile/chip/expand.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
arreglao

2023-12-29 09:21 UTC, Noralgorithm commented on src/lib/components/profile/add/Add.svelte
> +</button>
arreglo

2023-12-29 10:21 UTC, Noralgorithm commented on src/lib/components/profile/textbox/Textbox.svelte
> +        {disabled}
XD

2023-12-29 10:50 UTC, Noralgorithm commented on src/lib/profile/experience/validate-academic-experience.ts
> +  entryDate: date().nullable().default(null).required('Campo requerido'),
cierto, arreglao

2023-12-30 00:42 UTC, Hector1567XD reviewed
DIABLAZO

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/profile/experience/validate-academic-experience.ts
> +  freelancer: boolean(),
Eso lo que haría es que si pasas la propiedad freelancer como undefined al ```.validate()``` entonces se validaría como correcto, lo cual no tiene sentido en nuestro caso. Lo que sí le veo sentido ahora que me doy cuenta, es a colocarle un ```.required()```

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/profile/personal-information/validate-personal-information.ts
> +  email: string().required('Campo requerido').email('Email inválido'),
Hay que hablar eso, porque tenía entendido que al actualizar tu información personal el correo no tiene que ser necesariamente UCAB, porque si bien el correo UCAB es con el que se inicializa tu perfil, a la final tú colocas el correo con el que quieres que te contacten.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/profile/portfolio/project-creation-payload.type.ts
> +  images: Array<File | null>
Es lo segundo

https://bobbyhadz.com/blog/typescript-array-with-multiple-types

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/profile/portfolio/project-edition-payload.ts
> +  images: Array<File | null>
Es lo segundo

https://bobbyhadz.com/blog/typescript-array-with-multiple-types

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/api/profile/personal-information/update/+server.ts
> +export async function PUT({ request, fetch }: { request: Request; fetch: typeof window.fetch }) {
XD

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/+layout.server.ts
> +  params: { id },
En esa línea estoy destructurando la propiedad id del objeto params, no es tipado

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/Header.svelte
> +  $: currentRoute = $page.url.pathname.split('/').pop() as 'education' | 'experience' | 'portfolio'
Sí, para que se actualize la variable cada que cambia la ruta

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/education/Languages.svelte
> +      <h2>Idiomas</h2>
feat: add capitalize class

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/education/LanguagesDetailsModal.svelte
> +          <option value={langData.languageId}>{langData.name}</option>
Es el lenguaje que ya tiene puesto esa entrada que vas a editar, lo hago porque en la lista de los lenguajes que te recomienda no están los que tienes ya subidos a tu perfil

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/experience/+page.svelte
> +</div>
El problema de esto es que ya existe una etiqueta main en el [id=profle_id]/layout.svelte

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/portfolio/+page.svelte
> +</div>
Lo que sucede acá es que existe ya una etiqueta main en el [id=profile_id]/+layout.svelte

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +    formData.images.push(null)
Para añadir un Image Input sin imágen al final cuando se llene el array

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/profile/[id=profile_id]/portfolio/ProjectCreationModal.svelte
> +    formData.images.push(null)
En la línea anterior elimino todos los null y luego añado uno que representa el Image Input vacío al final (Esto es para cuando se elimina una imágen)

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/components/profile/chip/expand.ts
> +      }
Sí, esto es para que el expand se reproduzca al revés cuando ```isExpanded``` sea ```false```. 

```shrink``` es una animación que como estado inicial tiene el widht del elemento y lo reduce 40px, mientras que ```expand``` aumenta el width del elemento en 40px, por lo cual una animación no se corresponde con la inversa de la otra.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/components/profile/chip/expand.ts
> +      }
Lo expliqué en el otro comentario.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/components/profile/chip/Chip.svelte
> +  export let key: string
Eso es para poder usar el ```animate:flip``` en los Chips.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/components/profile/empty-list-message/EmptyListMessage.svelte
Ya lo borro XD

Ese es el componente del mensaje para cuando uno de los apartados del perfil está vacío, pero no lo hecho. Vamos a dejarlo como un improvement que se puede hacer a corto plazo.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/components/sign-up-log-in-switch-button/SignUpLogInSwitchButton.svelte
No lo borro todavía porque se va a romper el login que está actualmente en esta rama.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/components/sign-up-log-in-switch-button/sign-up-log-in-switch-button.test.ts
No lo borro todavía porque se va a romper el login que está actualmente en esta rama.

2023-12-30 01:01 UTC, Noralgorithm commented on src/lib/profile/portfolio/validate-project.ts
Lo mejoré y le añadí lo de que mínimo debe haber una imágen aparte de la del cover

```ts
const schema = object({
  name: string().required('Campo requerido'),
  description: string().required('Campo requerido'),
  projectUrl: string().url('URL inválida').optional(),
  coverImage: file().required('Campo requerido'),
  images: array().of(file()).min(1).required('Campo requerido')
})

function file() {
  return mixed((input: unknown): input is File => input instanceof File)
}
```

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/api/profile/portfolio/projects/create/+server.ts
Es que acá lo que se recibe es literalmente un FormData, no un JSON.

2023-12-30 01:01 UTC, Noralgorithm commented on src/routes/api/profile/portfolio/projects/update/+server.ts
Es que acá lo que se recibe es literalmente un FormData, no un JSON.

2024-01-03 06:43 UTC, DaikoneKisu commented on src/lib/components/profile/chip/expand.ts
> +      }
Ok, voy a hacer resolve a la conversation porque entiendo que sí es necesario, pero me lo explicas mejor luego

2024-01-03 06:44 UTC, DaikoneKisu commented on src/lib/components/profile/chip/expand.ts
> +      }
Lo mismo que respondí al otro comentario

2024-01-03 06:46 UTC, DaikoneKisu commented on src/lib/components/profile/chip/Chip.svelte
> +  export let key: string
Ok

2024-01-03 23:51 UTC, DaikoneKisu approved these changes
lgtm

2024-01-05 22:51 UTC, Paulaforero approved these changes

2024-01-05 23:25 UTC, merged